### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by Rifat8080** [Rifat8080/recipe-app-ruby#15]
Dear reviewer,

This is our project link:
https://github.com/Rifat8080/recipe-app-ruby/projects/1

We are a team of 3 members:
 @Rifat8080 
 @erickma1 
 @Nuga0909

**Comment by souad988** [comment]
Great work @Rifat8080, @Nuga0909 and @erickma1  👍🏼  👍🏼  👍🏼.
Highlight:

- The Kanban board includes all tasks from the project requirements.
- All cards have a proper title and description.
- All cards have points based on difficulty.
- All tasks are assigned to a team member

To change:
- Please make sure to equally distribute tasks between you, as now there is a difference of 5 points between @Rifat8080  and @erickma1.

**Comment by omar-muhamad** [comment]
# Approved ✔
### Hi Team,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to close this issue and start working on the project :shipit: 

### GOOD LUCK 🤞 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
